### ISSUE TITLE
Download but no prompt to save in Firefox

### ISSUE THREAD

**Issue by RutD0g** [puemos/hls-downloader#102]
**Describe the bug**

First, video downloaded (very quickly) to 100%, but I was never prompted to save it. (Can you tell me workaround, where to find it, like the blob data folder in Chrome?)

Seeing other bug reports from Chrome that smaller files might work, I went back to try a lower resolution -- and it says "No playlists found."

**To Reproduce**

https://video.foxnews.com/v/6161483471001#sp=show-clips

Windows 10 Home
Firefox 77.0
Opera 68.0.3618.125

**Comment by puemos** [comment]
Thanks @RutD0g, should be solved on https://github.com/puemos/hls-downloader/releases/tag/v3.2.1, if you have time let me know if it's working for you
