### ISSUE TITLE
Audio download via EXT-X-MEDIA

### ISSUE THREAD

**Issue by mattbasta** [puemos/hls-downloader#155]
**Is your feature request related to a problem? Please describe.**
I've been trying to archive a series of videos, but they are downloaded without audio. The m3u8 file looks like this:

```
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-medium",NAME="audio",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="..."
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-high",NAME="audio",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="..."

#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=320071,AVERAGE-BANDWIDTH=248000,RESOLUTION=426x240,FRAME-RATE=23.976,CODECS="avc1.640015,mp4a.40.2",AUDIO="audio-medium"
...
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=515891,AVERAGE-BANDWIDTH=383000,RESOLUTION=640x360,FRAME-RATE=23.976,CODECS="avc1.64001E,mp4a.40.2",AUDIO="audio-medium"
...
```
URLs to other m3u8 files have been replaced with `...`.

HLS downloader seems to be recognizing the `EXT-X-STREAM` m3u8 files, which contain only video. However, the `EXT-X-MEDIA` link (via `URI="..."`) to m3u8 files which contain the audio for the videos. These seem to be ignored by HLS downloader. Because the audio tracks are ignored, the downloaded files lack audio.

**Describe the solution you'd like**
I'd like to request support for these linked m3u8 files to be added, so that audio can be downloaded.

**Describe alternatives you've considered**
Currently my only option is to use a tool other than HLS downloader to capture these streams.

**Additional context**
I'd love to potentially contribute, but it's unclear where exactly to begin. Any tips would be appreciated.

**Comment by puemos** [comment]
Hey @mattbasta, sorry for the very long delay, can you share an example file?

**Comment by mattbasta** [comment]
I'm afraid I no longer have access to the files. I ended up doing the work with ffmpeg directly. Sorry!
