### ISSUE TITLE
It does not show play list in mongard.ir

### ISSUE THREAD

**Issue by guoard** [puemos/hls-downloader#156]
**Describe the bug**
I tried to download a video but your plugin does not work on any video in "mongard.ir"

**Desktop (please complete the following information):**
 - OS: [windows and ubuntu]
 - Browser [chrome]

**Comment by amirbigg** [comment]
Hi
i'm the owner of mongard.ir
this is not really a bug in hls-web-extension.
you cant download any of my videos :)

**Comment by guoard** [comment]
Hi Mr. Amir
I mean any sites which use blob protocol to stream videos and your website is just an example.
