### ISSUE TITLE
Concurrency option doesn't work!

### ISSUE THREAD

**Issue by MrMoHanD** [puemos/hls-downloader#171]
First, what do you mean by Concurrency? is it the number of files being downloaded at the same time or the number of max connection for each file like IDM does (it splits the file to multiple "sub-files" so it can download it faster!

well, if it is the number of files being downloaded at the same time, I want to tell you that the option isn't working.
even if I set Concurrency to 1, the extension still download all the files at the same time!

**Comment by puemos** [comment]
@MrMoHanD

Every HLS (HTTP live stream) is composed of multiple segments, together they are creating the full video, the "Concurrency" function is controlling of many of segments will be downloaded concurrently (and not sequentially)
