### ISSUE TITLE
Firefox no permanent installation method

### ISSUE THREAD

**Issue by vwheezy22** [puemos/hls-downloader#205]
This is a mild continuation of #178.

Previously, I could install the extension in Firefox's about:debugging page but I could not "install add-on from file" in the about:addons page. 

I found [this](https://stackoverflow.com/questions/62237202/firefox-add-ons-how-to-install-my-own-local-add-on-extension-permanently-in-f) SO thread that basically states everything you need to fix it.

After adding the changes (full `manifest.json` listed below) and repackaging, my error changed from failing to install because of "corruption" to failing to install because the extension is unverified.

[This](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox) post lists two about:config options: `xpinstall.signatures.required` and `extensions.langpacks.signatures.required`, but apparently they're only respected in ESR, Dev Edition, and Nightly versions.

I realize from #134 that Mozilla removed the extension, but I'm not sure if that affects if the extension is signable or not. Regardless, will there any way around this in the future besides either getting the extension back on the Addons page or switching to the Dev Edition?

<details><summary> manifest.json </summary>
Note: I'm not sure if the `content-scripts` field is needed and what to put in `id` for `browser_specific_settings`, putting anything made the error message change from corruption to unverification. 

```
{
    "short_name": "HLS Download",
    "name": "HLS Downloader",
    "description": "HTTP Live Stream downloader",
    "manifest_version": 2,
    "browser_action": {
        "default_popup": "index.html",
        "default_title": "HLS Downloader"
    },
    "version": "3.1.1",
    "background": {
        "scripts": ["background.js"],
        "persistent": true
    },
    "web_accessible_resources": ["assets/**/*"],
    "permissions": [
        "webRequest",
        "unlimitedStorage",
        "storage",
        "downloads",
        "tabs",
        "http://*/*",
        "https://*/*"
    ],
    "icons": {
        "16": "assets/icons/16.png",
        "48": "assets/icons/48.png",
        "128": "assets/icons/128.png",
        "256": "assets/icons/256.png"
    },
    "content-scripts" : [
        {
            "matches": ["*://*/*"]
        }
    ],
    "browser_specific_settings": {
        "gecko": {
            "id": "blahblah@blah"
        }
    }
}
```

</details>

**Comment by puemos** [comment]
Solved, now available on https://addons.mozilla.org/en-US/firefox/addon/hls-downloader/
