### ISSUE TITLE
Downloads fail - Firefox 91.0.1 "blob resource"

### ISSUE THREAD

**Issue by MathMike42** [puemos/hls-downloader#210]
Using version 3.1.2 it shows a completed download. When Firefox tries to complete the download, it fails with the message, "blob resource". I have replicated this same error on a couple of different websites. The only commonality is hls-downloader.

**Comment by puemos** [comment]
Thanks! I'm working on a solution here #207

**Comment by MathMike42** [comment]
Thank you!

**Comment by puemos** [comment]
Solved, now available on https://addons.mozilla.org/en-US/firefox/addon/hls-downloader/
