### ISSUE TITLE
MP4

### ISSUE THREAD

**Issue by YWYin1** [puemos/hls-downloader#213]
Can u add that we can convert it to MP4???

**Comment by MelanieTanaka** [comment]
Adding my support for this idea. Just got this plugin and was confused why the files are .ts, I assumed I would be getting .mp4 it's the standard these days. I tried to see if there was settings for it, found nothing and came to github to ask about it.

**Comment by darkesth2o** [comment]
I also would like to be able to set output to mp4 and not ts.

**Comment by shape55** [comment]
This is the sole reason why I clicked the Github link for this add-on.  It seems odd that there wouldn't be an option to convert files to mp4, as it's a much more universal format.  Please add this!

**Comment by puemos** [comment]
Done in v4
