### ISSUE TITLE
Console logging playlists/fetchPlaylistLevelsFailed for all Twitch VODs

### ISSUE THREAD

**Issue by jasonw4331** [puemos/hls-downloader#292]
**Description:**
Failure to register m3u8 contents as a playlist.

**To Reproduce:**

1. Go to any twitch.tv VOD.
2. Click on the HLS extension.
3. Notice there is no registered playlist for the VOD. Only live content appears.
4. Manually enter m3u8 URL (found through the network tab in devtools).
5. Notice HLS hangs while being unable to register playlist contents.

**Expected behavior**
HLS should properly parse the playlist file and read the referred files.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 1.56.20 Chromium: 115.0.5790.171 (Official Build)  (64-bit)

**Additional context**
[Console debug output.log](https://github.com/puemos/hls-downloader/files/12640288/console.debug.output.log)
[Main playlist file 1924021121.m3u8.txt](https://github.com/puemos/hls-downloader/files/12640270/1924021121.m3u8.txt)
[Secondary Referenced file index-dvr.m3u8.txt](https://github.com/puemos/hls-downloader/files/12640271/index-dvr.m3u8.txt)

**Comment by suklaalkmim** [comment]
I have the same behavior on Hotmart since last week. Tried the HLS with Chrome or Firefox.

OS: Mac OS Ventura
Version: 13.2.1 (22D68)
Chrome Version: 118.0.5993.88 (Official Build) (arm64)
Firefox Version: 118.0.2 (64-bits)

**Comment by Porkechebure** [comment]
Check this, at least I've found a way to do something while we wait a fix
#295
