### ISSUE TITLE
Direct Tab

### ISSUE THREAD

**Issue by Dave0T0** [puemos/hls-downloader#338]
Please add Direct tab back, why was it removed? I am having to use older version that still have this useful feature :(

**Comment by puemos** [comment]
I'll work on reintroducing this feature in v4

**Comment by shape55** [comment]
Great – thank you.

**Comment by puemos** [comment]
Done in [v4.1.0](https://github.com/puemos/hls-downloader/releases/tag/v4.1.0).
Will be released to Firefox in the next days

**Comment by Dave0T0** [comment]
> I'll work on reintroducing this feature in v4

Thank you :) :+1:
