### ISSUE TITLE
Cannot pause and resume automatically

### ISSUE THREAD

**Issue by shenfu1991** [puemos/hls-downloader#62]
Hi,

1 It cannot be paused and resumed automatically, sometimes it cannot be resumed after the network is disconnected

2  Removed videos cannot be downloaded again.

thanks.

**Comment by puemos** [comment]
Great idea, thanks!

**Comment by puemos** [comment]
@shenfu1991 solved in https://github.com/puemos/hls-downloader/releases/tag/v3.2.0
