### ISSUE TITLE
Firefox Dev Edition blob: download fails

### ISSUE THREAD

**Issue by Phoenix-Starlight** [puemos/hls-downloader#90]
**Describe the bug**
This is on Firefox Developer Edition 76.0b8 aurora channel. So what happens is that when it finishes the processing and commences download it says the download of blob: failed. Retrying does nothing and keeps on failing. This was tested on watch.pokemon.tv
**To Reproduce**
1. Go to 'HLS downloader extension'
2. Download any video at watch.pokemon.tv
3. Wait for download to commence.

**Expected behavior**
That it would download.

**Desktop (please complete the following information):**
 - OS: Win 8.1
 - Browser Firefox Dev Edition 76.0b8 aurora channel
 - Version 2.1.1

**Additional context**
It works on google chrome.

**Comment by puemos** [comment]
Thanks! @Phoenix-Starlight 
Solved on https://github.com/puemos/hls-downloader/releases/tag/v3.2.1
