### ISSUE TITLE
Concurrency not respected

### ISSUE THREAD

**Issue by johnfraser** [puemos/hls-downloader#99]
Just tried downloading several videos from telefe.com, and changed the concurrency from 2 to 3. The plugin proceded to download over 10 videos simultaneously.

**Comment by cooboodo** [comment]
Me too, I set 1 on Concurrency but download could not be done in a sequential order.

**Comment by puemos** [comment]
@johnfraser @cooboodo 

Every HLS (HTTP live stream) is composed of multiple segments, together they are creating the full video, the "Concurrency" function is controlling of many of segments will be downloaded concurrently (and not sequentially)

I will change the label on the setting page to "Segments' Concurrency"
